### ISSUE TITLE
Day 18 Lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/GitHubProject#11]
You are still missing the following technical requirements:

- Layout your TableViewCells as Nibs and create a subclass called RepositoryCell instead of using the Basic UITableViewCell.

- Your Nib should have UILabels for 3 pieces of data from the Repository:
-- Repo Name
-- Repo Description
-- Repo Language

- Implement the dismissal of the RepoDetailViewController.

- Your RepoDetailViewController should display at least these 6 pieces of data from the Repository:
--Repo Name
--Repo Description
--Programming Language
--Number Of Stars
--isFork: True or False
--createdAt: Date

**Comment by thegrimheep** [comment]
I have these features working.
