### ISSUE TITLE
Day 16 lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/GitHubProject#4]
You're still missing the following technical requirements:

- Implement UserDefaults, for today, to store the access_token, so the user only needs to go through the OAuth process once. _(If a token exists, `LOGIN` button should be disabled.)_
- On launch, your application needs to check if there is an existing access_token in UserDefaults. If there is, disable the login button. _(When I click on the `PRINT TOKEN` button, the access token should print to the console.)_

**Comment by thegrimheep** [comment]
I have completed the other requirements.
