### ISSUE TITLE
Day 17 Lab - Repos do not show after initial login

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/GitHubProject#8]
When I log in to Github the first time through your app, the list of repos does not populate. 

This is because you're checking to see if an `access_token` exists when you initialize your `GitHub` singleton, but the first time the app is run this happens **before** a token exists. You can fix this by moving the part of the initializer where you check for the token into the beginning of your `getRepos` method.

This is the code I'm referring to:

```
if let token = UserDefaults.standard.getAccessToken() {
            let queryItem = URLQueryItem(name: "access_token", value: token)
            self.components.queryItems = [queryItem]
        }
```

**Comment by thegrimheep** [comment]
This issue has been resolved.
